SHIP_NAME = 'Ship_{}'
WEAPON_NAME = 'Weapon_{}'
HULL_NAME = 'Hull_{}'
ENGINE_NAME = 'Engine_{}'

DEFAULT_NUMBER_OF_SHIPS = 200
DEFAULT_NUMBER_OF_WEAPONS = 20
DEFAULT_NUMBER_OF_HULLS = 5
DEFAULT_NUMBER_OF_ENGINES = 6

DEFAULT_DB_NAME = 'test_ships.db'
